{
 "title": "Grids team dashboard",
 "time": { "from": "2023-06-06T20:00:00.000Z", "to": "2023-08-31T19:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "DB_METRICS_DATASOURCE", "label": "Datasource variable", "query": "mssql" },
   {
    "name": "employee_id",
    "label": "Team member",
    "query": "Alyar_S : 5316bd314b41c8ac4155a79f, Andrew_D : 561e8894fb47c289aa122dec, Andrew_M : 525d5151aa3d4e2512000a4e, Eldar_I : 62f5ff4ae1d51c222f3d8334, Ilya_V : 629db35c3c001407334e5ab3, Roman_S : 609a78f4a5c6ab080f270c56"
   }
  ]
 },
 "panels": [
  {
   "title": "ETA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Card average ETA",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "select \n\tavg(tc.duration_minutes / (60 * 24.0)) as eta\nfrom trello_cards tc \ninner join trello_card_label_relation tclr \non tclr.trello_card_id = tc.trello_id \nleft join trello_labels tl \non tl.trello_id = tclr.trello_label_id \ninner join trello_card_member_relation tcmr \non tcmr.trello_card_id = tc.trello_id\nwhere tl.name like 'type:%' \n\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\tand tcmr.trello_member_id in (${employee_id})"
      }
     ]
    },
    {
     "title": "🛠️ Doing average time",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "select \n\tavg(eta) as ETA\nfrom (\nselect \n\ttc.trello_id,\n\tsum(tch.duration_minutes / (24.0 * 60)) as eta\nfrom trello_cards tc \ninner join trello_card_label_relation tclr \non tclr.trello_card_id = tc.trello_id \nleft join trello_labels tl \non tl.trello_id = tclr.trello_label_id \ninner join trello_card_member_relation tcmr \non tcmr.trello_card_id = tc.trello_id\nleft join trello_card_history tch \non tch.trello_card_id = tc.trello_id\nwhere tl.name like 'type:%' \n\tand tch.trello_list_id = '5a2fc0b811bfc2a9b31cc852'\n\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\tand tcmr.trello_member_id in (${employee_id})\ngroup by tc.trello_id\n) as result"
      }
     ]
    },
    {
     "title": "👀 Review average time",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "select \n\tavg(eta) as ETA\nfrom (\nselect \n\ttc.trello_id,\n\tsum(tch.duration_minutes / (24.0 * 60)) as eta\nfrom trello_cards tc \ninner join trello_card_label_relation tclr \non tclr.trello_card_id = tc.trello_id \nleft join trello_labels tl \non tl.trello_id = tclr.trello_label_id \ninner join trello_card_member_relation tcmr \non tcmr.trello_card_id = tc.trello_id\nleft join trello_card_history tch \non tch.trello_card_id = tc.trello_id\nwhere tl.name like 'type:%' \n\tand tch.trello_list_id = '5a2fc0d2da16f4a190bcb5e3'\n\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\tand tcmr.trello_member_id in (${employee_id})\ngroup by tc.trello_id\n) as result"
      }
     ]
    },
    {
     "title": "👏 Ready to merge average time",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 15, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "select \n\tavg(eta) as ETA\nfrom (\nselect \n\ttc.trello_id,\n\tsum(tch.duration_minutes / (24.0 * 60)) as eta\nfrom trello_cards tc \ninner join trello_card_label_relation tclr \non tclr.trello_card_id = tc.trello_id \nleft join trello_labels tl \non tl.trello_id = tclr.trello_label_id \ninner join trello_card_member_relation tcmr \non tcmr.trello_card_id = tc.trello_id\nleft join trello_card_history tch \non tch.trello_card_id = tc.trello_id\nwhere tl.name like 'type:%' \n\tand tch.trello_list_id = '64abb4da74aacfb1812e144a'\n\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\tand tcmr.trello_member_id in (${employee_id})\ngroup by tc.trello_id\n) as result"
      }
     ]
    },
    {
     "title": "🐞 Bug average time ETA",
     "type": "table",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "select\n\tbug_complexity as Complexity,\n\tavg(eta) as ETA\nfrom (\n\tselect\n\t\ttc.trello_id as card_id,\n\t\tcase \n\t\t\twhen tc.score <= 3 then '1 easy'\n\t\t\twhen tc.score = 5 then '2 middle'\n\t\t\telse '3 hard'\n\t\tend as bug_complexity,\n\t\ttc.duration_minutes / (24.0 * 60) as eta\n\tfrom trello_cards tc \n\tleft join trello_card_label_relation tclr \n\ton tclr.trello_card_id = tc.trello_id \n\tleft join trello_labels tl \n\ton tl.trello_id  = tclr.trello_label_id \n\tinner join trello_card_member_relation tcmr \n\ton tcmr.trello_card_id = tc.trello_id \n\twhere tl.name like 'type: bug%'\n\t\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\tand tcmr.trello_member_id in (${employee_id})\n) as result\ngroup by bug_complexity"
      }
     ]
    },
    {
     "title": "🛠️ Bug average time in doing",
     "type": "table",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "select\n\tbug_complexity as Complexity,\n\tavg(eta) as ETA\nfrom (\n\tselect\n\t\ttc.trello_id as card_id,\n\t\tcase \n\t\t\twhen tc.score <= 3 then '1 easy'\n\t\t\twhen tc.score = 5 then '2 middle'\n\t\t\telse '3 hard'\n\t\tend as bug_complexity,\n\t\tsum(tch.duration_minutes / (24.0 * 60)) as eta\n\tfrom trello_cards tc \n\tleft join trello_card_label_relation tclr \n\ton tclr.trello_card_id = tc.trello_id \n\tleft join trello_labels tl \n\ton tl.trello_id  = tclr.trello_label_id \n\tinner join trello_card_member_relation tcmr \n\ton tcmr.trello_card_id = tc.trello_id \n\tleft join trello_card_history tch \n\ton tch.trello_card_id = tc.trello_id\n\twhere tl.name like 'type: bug%'\n\t\tand tch.trello_list_id = '5a2fc0b811bfc2a9b31cc852'\n\t\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\tand tcmr.trello_member_id in (${employee_id})\n\tgroup by tc.trello_id, tc.score\n) as result\ngroup by bug_complexity"
      }
     ]
    },
    {
     "title": "👀 Bug average time in review",
     "type": "table",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "select\n\tbug_complexity as Complexity,\n\tavg(eta) as ETA\nfrom (\n\tselect\n\t\ttc.trello_id as card_id,\n\t\tcase \n\t\t\twhen tc.score <= 3 then '1 easy'\n\t\t\twhen tc.score = 5 then '2 middle'\n\t\t\telse '3 hard'\n\t\tend as bug_complexity,\n\t\tsum(tch.duration_minutes / (24.0 * 60)) as eta\n\tfrom trello_cards tc \n\tleft join trello_card_label_relation tclr \n\ton tclr.trello_card_id = tc.trello_id \n\tleft join trello_labels tl \n\ton tl.trello_id  = tclr.trello_label_id \n\tinner join trello_card_member_relation tcmr \n\ton tcmr.trello_card_id = tc.trello_id \n\tleft join trello_card_history tch \n\ton tch.trello_card_id = tc.trello_id\n\twhere tl.name like 'type: bug%'\n\t\tand tch.trello_list_id = '5a2fc0d2da16f4a190bcb5e3'\n\t\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\tand tcmr.trello_member_id in (${employee_id})\n\tgroup by tc.trello_id, tc.score\n) as result\ngroup by bug_complexity"
      }
     ]
    },
    {
     "title": "👏 Bug average time in ready to merge",
     "type": "table",
     "gridPos": { "h": 7, "w": 5, "x": 15, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "select\n\tbug_complexity as Complexity,\n\tavg(eta) as ETA\nfrom (\n\tselect\n\t\ttc.trello_id as card_id,\n\t\tcase \n\t\t\twhen tc.score <= 3 then '1 easy'\n\t\t\twhen tc.score = 5 then '2 middle'\n\t\t\telse '3 hard'\n\t\tend as bug_complexity,\n\t\tsum(tch.duration_minutes / (24.0 * 60)) as eta\n\tfrom trello_cards tc \n\tleft join trello_card_label_relation tclr \n\ton tclr.trello_card_id = tc.trello_id \n\tleft join trello_labels tl \n\ton tl.trello_id  = tclr.trello_label_id \n\tinner join trello_card_member_relation tcmr \n\ton tcmr.trello_card_id = tc.trello_id \n\tleft join trello_card_history tch \n\ton tch.trello_card_id = tc.trello_id\n\twhere tl.name like 'type: bug%'\n\t\tand tch.trello_list_id = '64abb4da74aacfb1812e144a'\n\t\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\tand tcmr.trello_member_id in (${employee_id})\n\tgroup by tc.trello_id, tc.score\n) as result\ngroup by bug_complexity"
      }
     ]
    },
    {
     "title": "Other cards ETA",
     "type": "table",
     "gridPos": { "h": 11, "w": 5, "x": 0, "y": 16 },
     "targets": [
      {
       "rawSql": "select\n\ttype as Type,\n\tavg(eta) as ETA\nfrom (\n\tselect\n\t\ttc.trello_id as card_id,\n\t\ttl.name as type,\n\t\ttc.duration_minutes / (24.0 * 60) as eta\n\tfrom trello_cards tc \n\tleft join trello_card_label_relation tclr \n\ton tclr.trello_card_id = tc.trello_id \n\tleft join trello_labels tl \n\ton tl.trello_id  = tclr.trello_label_id \n\tinner join trello_card_member_relation tcmr \n\ton tcmr.trello_card_id = tc.trello_id \n\twhere tl.name like 'type:%' \n    and tl.name not like '%bug%'\n\t\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\tand tcmr.trello_member_id in (${employee_id})\n) as result\ngroup by type\n\n"
      }
     ]
    },
    {
     "title": "🛠️ Other cards time in doing",
     "type": "table",
     "gridPos": { "h": 11, "w": 5, "x": 5, "y": 16 },
     "targets": [
      {
       "rawSql": "select\n\ttype as Type,\n\tavg(eta) as ETA\nfrom (\n\tselect\n\t\ttc.trello_id as card_id,\n\t\ttl.name as type,\n\t\tsum(tch.duration_minutes / (24.0 * 60)) as eta\n\tfrom trello_cards tc \n\tleft join trello_card_label_relation tclr \n\ton tclr.trello_card_id = tc.trello_id \n\tleft join trello_labels tl \n\ton tl.trello_id  = tclr.trello_label_id \n\tinner join trello_card_member_relation tcmr \n\ton tcmr.trello_card_id = tc.trello_id \n\tleft join trello_card_history tch \n\ton tch.trello_card_id = tc.trello_id\n\twhere tl.name like 'type:%' \n    \tand tl.name not like '%bug%'\n    \tand tch.trello_list_id = '5a2fc0b811bfc2a9b31cc852'\n\t\t\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\t\tand tcmr.trello_member_id in (${employee_id})\n\tgroup by tc.trello_id, tl.name\n) as result\ngroup by type\n\n"
      }
     ]
    },
    {
     "title": "👀 Other cards time in review",
     "type": "table",
     "gridPos": { "h": 11, "w": 5, "x": 10, "y": 16 },
     "targets": [
      {
       "rawSql": "select\n\ttype as Type,\n\tavg(eta) as ETA\nfrom (\n\tselect\n\t\ttc.trello_id as card_id,\n\t\ttl.name as type,\n\t\tsum(tch.duration_minutes / (24.0 * 60)) as eta\n\tfrom trello_cards tc \n\tleft join trello_card_label_relation tclr \n\ton tclr.trello_card_id = tc.trello_id \n\tleft join trello_labels tl \n\ton tl.trello_id  = tclr.trello_label_id \n\tinner join trello_card_member_relation tcmr \n\ton tcmr.trello_card_id = tc.trello_id \n\tleft join trello_card_history tch \n\ton tch.trello_card_id = tc.trello_id\n\twhere tl.name like 'type:%' \n    \tand tl.name not like '%bug%'\n    \tand tch.trello_list_id = '5a2fc0d2da16f4a190bcb5e3'\n\t\t\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\t\tand tcmr.trello_member_id in (${employee_id})\n\tgroup by tc.trello_id, tl.name\n) as result\ngroup by type\n\n"
      }
     ]
    },
    {
     "title": "👏 Other cards time in ready to merge",
     "type": "table",
     "gridPos": { "h": 11, "w": 5, "x": 15, "y": 16 },
     "targets": [
      {
       "rawSql": "select\n\ttype as Type,\n\tavg(eta) as ETA\nfrom (\n\tselect\n\t\ttc.trello_id as card_id,\n\t\ttl.name as type,\n\t\tsum(tch.duration_minutes / (24.0 * 60)) as eta\n\tfrom trello_cards tc \n\tleft join trello_card_label_relation tclr \n\ton tclr.trello_card_id = tc.trello_id \n\tleft join trello_labels tl \n\ton tl.trello_id  = tclr.trello_label_id \n\tinner join trello_card_member_relation tcmr \n\ton tcmr.trello_card_id = tc.trello_id \n\tleft join trello_card_history tch \n\ton tch.trello_card_id = tc.trello_id\n\twhere tl.name like 'type:%' \n    \tand tl.name not like '%bug%'\n    \tand tch.trello_list_id = '64abb4da74aacfb1812e144a'\n\t\t\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\t\tand tcmr.trello_member_id in (${employee_id})\n\tgroup by tc.trello_id, tl.name\n) as result\ngroup by type\n\n"
      }
     ]
    },
    {
     "title": "🏝️ Waiting average time",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "select \n\tavg(eta) as ETA\nfrom (\nselect \n\ttc.trello_id,\n\tsum(tch.duration_minutes / (24.0 * 60)) as eta\nfrom trello_cards tc \ninner join trello_card_label_relation tclr \non tclr.trello_card_id = tc.trello_id \nleft join trello_labels tl \non tl.trello_id = tclr.trello_label_id \ninner join trello_card_member_relation tcmr \non tcmr.trello_card_id = tc.trello_id\nleft join trello_card_history tch \non tch.trello_card_id = tc.trello_id\nwhere tl.name like 'type:%' \n\tand tch.trello_list_id = '5a2fc0caee2889ee4735dfd4'\n\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\tand tcmr.trello_member_id in (${employee_id})\ngroup by tc.trello_id\n) as result"
      }
     ]
    },
    {
     "title": "ETA dynamic",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 15, "x": 5, "y": 27 },
     "targets": [
      {
       "rawSql": "select \n\ttl.name as Type,\n\tDATETRUNC(week, DATEADD(week, 1, tc.done_time)) as Week,\n\tavg(tc.duration_minutes / (24.0 * 60)) as Eta\nfrom trello_cards tc \nleft join trello_card_label_relation tclr \non tclr.trello_card_id = tc.trello_id \nleft join trello_labels tl \non tl.trello_id = tclr.trello_label_id \nwhere tl.name like 'type%'\ngroup by tl.name, DATETRUNC(week, DATEADD(week, 1, tc.done_time))\n"
      }
     ]
    },
    {
     "title": "🏝️ Bug average time in waiting",
     "type": "table",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "select\n\tbug_complexity as Complexity,\n\tavg(eta) as ETA\nfrom (\n\tselect\n\t\ttc.trello_id as card_id,\n\t\tcase \n\t\t\twhen tc.score <= 3 then '1 easy'\n\t\t\twhen tc.score = 5 then '2 middle'\n\t\t\telse '3 hard'\n\t\tend as bug_complexity,\n\t\tsum(tch.duration_minutes / (24.0 * 60)) as eta\n\tfrom trello_cards tc \n\tleft join trello_card_label_relation tclr \n\ton tclr.trello_card_id = tc.trello_id \n\tleft join trello_labels tl \n\ton tl.trello_id  = tclr.trello_label_id \n\tinner join trello_card_member_relation tcmr \n\ton tcmr.trello_card_id = tc.trello_id \n\tleft join trello_card_history tch \n\ton tch.trello_card_id = tc.trello_id\n\twhere tl.name like 'type: bug%'\n\t\tand tch.trello_list_id = '5a2fc0caee2889ee4735dfd4'\n\t\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\tand tcmr.trello_member_id in (${employee_id})\n\tgroup by tc.trello_id, tc.score\n) as result\ngroup by bug_complexity"
      }
     ]
    },
    {
     "title": "🏝️ Other cards time in waiting",
     "type": "table",
     "gridPos": { "h": 11, "w": 5, "x": 0, "y": 43 },
     "targets": [
      {
       "rawSql": "select\n\ttype as Type,\n\tavg(eta) as ETA\nfrom (\n\tselect\n\t\ttc.trello_id as card_id,\n\t\ttl.name as type,\n\t\tsum(tch.duration_minutes / (24.0 * 60)) as eta\n\tfrom trello_cards tc \n\tleft join trello_card_label_relation tclr \n\ton tclr.trello_card_id = tc.trello_id \n\tleft join trello_labels tl \n\ton tl.trello_id  = tclr.trello_label_id \n\tinner join trello_card_member_relation tcmr \n\ton tcmr.trello_card_id = tc.trello_id \n\tleft join trello_card_history tch \n\ton tch.trello_card_id = tc.trello_id\n\twhere tl.name like 'type:%' \n    \tand tl.name not like '%bug%'\n    \tand tch.trello_list_id = '5a2fc0caee2889ee4735dfd4'\n\t\t\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\t\tand tcmr.trello_member_id in (${employee_id})\n\tgroup by tc.trello_id, tl.name\n) as result\ngroup by type\n\n"
      }
     ]
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Bug count dynamic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "select \n\tCOUNT(tc.trello_id) as bug_count,\n\tDATETRUNC(week, DATEADD(week, 1, tc.done_time)) as week \nfrom trello_cards tc \ninner join trello_card_label_relation tclr \non tclr.trello_card_id = tc.trello_id \ninner join trello_labels tl \non tl.trello_id = tclr.trello_label_id \nwhere tl.name like '%bug%'\ngroup by DATETRUNC(week, DATEADD(week, 1, tc.done_time))\nhaving DATETRUNC(week, DATEADD(week, 1, tc.done_time)) between '${__from:date:iso}' and '${__to:date:iso}'"
    }
   ]
  },
  {
   "title": "Task types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  tl.name,\n\tISNULL(SUM(score * 1.0 / mc.member_count), 0) as story_points\nfrom trello_cards tc \ninner join trello_card_label_relation tclr \non tclr.trello_card_id = tc.trello_id  \ninner join trello_labels tl \non tl.trello_id = tclr.trello_label_id\ninner join trello_card_member_relation tcmr \non tcmr.trello_card_id = tc.trello_id \ninner join (\n\t\tselect \n\t\t\ttc2.trello_id as card_id,\n\t\t\tcount(tcmr2.trello_member_id) as member_count\n\t\tfrom trello_cards tc2 \n\t\tleft join trello_card_member_relation tcmr2 \n\t\ton tcmr2.trello_card_id = tc2.trello_id\n\t\twhere tc2.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\tgroup by tc2.trello_id\n) as mc\non mc.card_id = tc.trello_id\nwhere tl.name like 'type:%'\n\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\tand tcmr.trello_member_id in (${employee_id})\ngroup by tl.name"
    }
   ]
  },
  {
   "title": "Team velocity (SP)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "select \n\ttm.full_name as assignee,\n\tDATETRUNC(week, DATEADD(week, 1, tc.done_time)) as week,\n\tISNULL(SUM(ts.score), 0) as points\nfrom trello_cards tc \ninner join (\n\tselect\n\t\ttrello_id,\n\t\t(score * 1.) / COUNT(tcmr_inner.id) as score\n\tfrom trello_cards tc_inner\n\tinner join trello_card_member_relation tcmr_inner\n\ton tcmr_inner.trello_card_id = tc_inner.trello_id \n\tgroup by trello_id, score\n) ts\non tc.trello_id = ts.trello_id\ninner join trello_card_member_relation tcmr2\non tcmr2.trello_card_id = tc.trello_id \ninner join trello_members tm \non tm.trello_id = tcmr2.trello_member_id \ngroup by tm.full_name, DATETRUNC(week, DATEADD(week, 1, tc.done_time))\nhaving DATETRUNC(week, DATEADD(week, 1, tc.done_time)) between '${__from:date:iso}' and '${__to:date:iso}'"
    }
   ]
  },
  {
   "title": "Team velocity impact (SP)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "select \n\ttm.full_name as assignee,\n\tDATETRUNC(week, DATEADD(week, 1, tc.done_time)) as week,\n\tISNULL(SUM(ts.score), 0) as points\nfrom trello_cards tc \ninner join (\n\tselect\n\t\ttrello_id,\n\t\t(score * 1.) / COUNT(tcmr_inner.id) as score\n\tfrom trello_cards tc_inner\n\tinner join trello_card_member_relation tcmr_inner\n\ton tcmr_inner.trello_card_id = tc_inner.trello_id \n\tgroup by trello_id, score\n) ts\non tc.trello_id = ts.trello_id\ninner join trello_card_member_relation tcmr2\non tcmr2.trello_card_id = tc.trello_id \ninner join trello_members tm \non tm.trello_id = tcmr2.trello_member_id \ngroup by tm.full_name, DATETRUNC(week, DATEADD(week, 1, tc.done_time))\nhaving DATETRUNC(week, DATEADD(week, 1, tc.done_time)) between '${__from:date:iso}' and '${__to:date:iso}'"
    }
   ]
  }
 ]
}