{
 "title": "Grids team dashboard",
 "time": { "from": "2023-06-06T20:00:00.000Z", "to": "2023-08-31T19:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "DB_METRICS_DATASOURCE", "label": "Datasource variable", "query": "mssql" }
  ]
 },
 "panels": [
  {
   "title": "🐞 Bug average time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \n  bt.trello_id,\n  SUM(tch.duration_minutes / (60 * 24)) as eta\nfrom (\n\tselect tc.trello_id from trello_cards tc \n\tinner join trello_card_label_relation tclr \n\ton tclr.trello_card_id = tc.trello_id \n\tinner join trello_labels tl \n\ton tl.trello_id = tclr.trello_label_id \n\twhere tl.name like '%bug%' and tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n) as bt\ninner join (\n\tselect * from trello_card_history tch_inner\n\twhere tch_inner.trello_list_id != '5a2fc0acdf6af93d3a7528c7'\n) as tch\non tch.trello_card_id = bt.trello_id \ngroup by bt.trello_id "
    }
   ]
  },
  {
   "title": "🛠️ Doing average time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \n  tl2.name,\n  bt.trello_id,\n  SUM(tch.duration_minutes) * 1. / (60 * 24) as eta\nfrom (\n\tselect tc.trello_id from trello_cards tc \n\tinner join trello_card_label_relation tclr \n\ton tclr.trello_card_id = tc.trello_id \n\tinner join trello_labels tl \n\ton tl.trello_id = tclr.trello_label_id \n\twhere tl.name like '%bug%' and tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n) as bt\ninner join trello_card_history tch \non tch.trello_card_id = bt.trello_id\ninner join (\n\tselect * from trello_lists tl_inner\n\twhere \n\ttl_inner.type = 0 \n\tand tl_inner.trello_id = '5a2fc0b811bfc2a9b31cc852'\n) as tl2\non tl2.trello_id = tch.trello_list_id \ngroup by tl2.name, bt.trello_id\t"
    }
   ]
  },
  {
   "title": "🏝️ Waiting average time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \n  tl2.name,\n  bt.trello_id,\n  SUM(tch.duration_minutes) * 1. / (60 * 24) as eta\nfrom (\n\tselect tc.trello_id from trello_cards tc \n\tinner join trello_card_label_relation tclr \n\ton tclr.trello_card_id = tc.trello_id \n\tinner join trello_labels tl \n\ton tl.trello_id = tclr.trello_label_id \n\twhere tl.name like '%bug%' and tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n) as bt\ninner join trello_card_history tch \non tch.trello_card_id = bt.trello_id\ninner join (\n\tselect * from trello_lists tl_inner\n\twhere \n\ttl_inner.type = 0 \n\tand tl_inner.trello_id = '5a2fc0caee2889ee4735dfd4'\n) as tl2\non tl2.trello_id = tch.trello_list_id \ngroup by tl2.name, bt.trello_id\t"
    }
   ]
  },
  {
   "title": "👀 Review average time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \n  tl2.name,\n  bt.trello_id,\n  SUM(tch.duration_minutes) * 1. / (60 * 24) as eta\nfrom (\n\tselect tc.trello_id from trello_cards tc \n\tinner join trello_card_label_relation tclr \n\ton tclr.trello_card_id = tc.trello_id \n\tinner join trello_labels tl \n\ton tl.trello_id = tclr.trello_label_id \n\twhere tl.name like '%bug%' and tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n) as bt\ninner join trello_card_history tch \non tch.trello_card_id = bt.trello_id\ninner join (\n\tselect * from trello_lists tl_inner\n\twhere \n\ttl_inner.type = 0 \n\tand tl_inner.trello_id = '5a2fc0d2da16f4a190bcb5e3'\n) as tl2\non tl2.trello_id = tch.trello_list_id \ngroup by tl2.name, bt.trello_id\t"
    }
   ]
  },
  {
   "title": "👏 Ready to merge average time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \n  tl2.name,\n  bt.trello_id,\n  SUM(tch.duration_minutes) * 1. / (60 * 24) as eta\nfrom (\n\tselect tc.trello_id from trello_cards tc \n\tinner join trello_card_label_relation tclr \n\ton tclr.trello_card_id = tc.trello_id \n\tinner join trello_labels tl \n\ton tl.trello_id = tclr.trello_label_id \n\twhere tl.name like '%bug%' and tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n) as bt\ninner join trello_card_history tch \non tch.trello_card_id = bt.trello_id\ninner join (\n\tselect * from trello_lists tl_inner\n\twhere \n\ttl_inner.type = 0 \n\tand tl_inner.trello_id = '64abb4da74aacfb1812e144a'\n) as tl2\non tl2.trello_id = tch.trello_list_id \ngroup by tl2.name, bt.trello_id\t"
    }
   ]
  },
  {
   "title": "Closed bug count (last)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n\tCOUNT(tc.trello_id) as bug_count,\n\tDATETRUNC(week, DATEADD(week, 1, tc.done_time)) as week \nfrom trello_cards tc \ninner join trello_card_label_relation tclr \non tclr.trello_card_id = tc.trello_id \ninner join trello_labels tl \non tl.trello_id = tclr.trello_label_id \nwhere tl.name like '%bug%'\ngroup by DATETRUNC(week, DATEADD(week, 1, tc.done_time))\nhaving DATETRUNC(week, DATEADD(week, 1, tc.done_time)) between '${__from:date:iso}' and '${__to:date:iso}'"
    }
   ]
  },
  {
   "title": "Bug count dynamic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 8 },
   "targets": [
    {
     "rawSql": "select \n\tCOUNT(tc.trello_id) as bug_count,\n\tDATETRUNC(week, DATEADD(week, 1, tc.done_time)) as week \nfrom trello_cards tc \ninner join trello_card_label_relation tclr \non tclr.trello_card_id = tc.trello_id \ninner join trello_labels tl \non tl.trello_id = tclr.trello_label_id \nwhere tl.name like '%bug%'\ngroup by DATETRUNC(week, DATEADD(week, 1, tc.done_time))\nhaving DATETRUNC(week, DATEADD(week, 1, tc.done_time)) between '${__from:date:iso}' and '${__to:date:iso}'"
    }
   ]
  },
  {
   "title": "Task types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n    tl.name,\n    DATETRUNC(week, DATEADD(week, 1, done_time)) as week,\n\tISNULL(SUM(score), 0) as story_points\nfrom trello_cards tc \ninner join trello_card_label_relation tclr \non tclr.trello_card_id = tc.trello_id  \ninner join trello_labels tl \non tl.trello_id = tclr.trello_label_id\ngroup by tl.name, DATETRUNC(week, DATEADD(week, 1, done_time))\nhaving \n\ttl.name like '%type:%' \n\tand DATETRUNC(week, DATEADD(week, 1, done_time)) between '${__from:date:iso}' and '${__to:date:iso}'"
    }
   ]
  },
  {
   "title": "Team velocity (SP)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select \n\ttm.full_name as assignee,\n\tDATETRUNC(week, DATEADD(week, 1, tc.done_time)) as week,\n\tISNULL(SUM(ts.score), 0) as points\nfrom trello_cards tc \ninner join (\n\tselect\n\t\ttrello_id,\n\t\t(score * 1.) / COUNT(tcmr_inner.id) as score\n\tfrom trello_cards tc_inner\n\tinner join trello_card_member_relation tcmr_inner\n\ton tcmr_inner.trello_card_id = tc_inner.trello_id \n\tgroup by trello_id, score\n) ts\non tc.trello_id = ts.trello_id\ninner join trello_card_member_relation tcmr2\non tcmr2.trello_card_id = tc.trello_id \ninner join trello_members tm \non tm.trello_id = tcmr2.trello_member_id \ngroup by tm.full_name, DATETRUNC(week, DATEADD(week, 1, tc.done_time))\nhaving DATETRUNC(week, DATEADD(week, 1, tc.done_time)) between '${__from:date:iso}' and '${__to:date:iso}'"
    }
   ]
  },
  {
   "title": "Team velocity impact (SP)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "select \n\ttm.full_name as assignee,\n\tDATETRUNC(week, DATEADD(week, 1, tc.done_time)) as week,\n\tISNULL(SUM(ts.score), 0) as points\nfrom trello_cards tc \ninner join (\n\tselect\n\t\ttrello_id,\n\t\t(score * 1.) / COUNT(tcmr_inner.id) as score\n\tfrom trello_cards tc_inner\n\tinner join trello_card_member_relation tcmr_inner\n\ton tcmr_inner.trello_card_id = tc_inner.trello_id \n\tgroup by trello_id, score\n) ts\non tc.trello_id = ts.trello_id\ninner join trello_card_member_relation tcmr2\non tcmr2.trello_card_id = tc.trello_id \ninner join trello_members tm \non tm.trello_id = tcmr2.trello_member_id \ngroup by tm.full_name, DATETRUNC(week, DATEADD(week, 1, tc.done_time))\nhaving DATETRUNC(week, DATEADD(week, 1, tc.done_time)) between '${__from:date:iso}' and '${__to:date:iso}'"
    }
   ]
  }
 ]
}