{
 "title": "Grids private dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DB_METRICS_DATASOURCE", "query": "mssql" },
   {
    "name": "employee_id",
    "label": "Team member",
    "query": "Alyar_S : 5316bd314b41c8ac4155a79f, Andrew_D : 561e8894fb47c289aa122dec, Andrew_M : 525d5151aa3d4e2512000a4e, Eldar_I : 62f5ff4ae1d51c222f3d8334, Ilya_V : 629db35c3c001407334e5ab3, Roman_S : 609a78f4a5c6ab080f270c56"
   }
  ]
 },
 "panels": [
  { "title": "Grids team", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Team spending",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n\ttl.name as label_name,\n\tsum((tch.duration_minutes * 1.0 / mc.member_count) / (24.0 * 60) * tm.salary_per_day) as cost\nfrom trello_cards tc \nleft join trello_card_label_relation tclr \non tclr.trello_card_id = tc.trello_id \nleft join trello_labels tl \non tl.trello_id = tclr.trello_label_id \ninner join trello_card_member_relation tcmr \non tcmr.trello_card_id = tc.trello_id \nleft join trello_members tm \non tm.trello_id = tcmr.trello_member_id\nleft join trello_card_history tch \non tch.trello_card_id = tc.trello_id \nleft join (\n\tselect \n\t\ttc2.trello_id as card_id,\n\t\tcount(tcmr2.trello_member_id) as member_count\n\tfrom trello_cards tc2 \n\tleft join trello_card_member_relation tcmr2 \n\ton tcmr2.trello_card_id = tc2.trello_id\n\twhere tc2.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\tgroup by tc2.trello_id\n) as mc\non mc.card_id = tc.trello_id\nwhere tl.name like 'type:%'\n\tand tch.trello_list_id = '5a2fc0b811bfc2a9b31cc852'\n\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\tand tm.trello_id in (${employee_id})\ngroup by tl.name"
    }
   ]
  },
  {
   "title": "Average card cost",
   "type": "table",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select \n\ttype as Type,\n\tAVG(cost) as Cost\nfrom (\n\tselect\n\t\ttc.trello_id as card_id,\n\t\ttl.name as type,\n\t\tsum((tch.duration_minutes / mc.member_count) / (24.0 * 60) * tm.salary_per_day) as cost\n\tfrom trello_cards tc \n\tleft join trello_card_label_relation tclr \n\ton tclr.trello_card_id = tc.trello_id \n\tleft join trello_labels tl \n\ton tl.trello_id  = tclr.trello_label_id \n\tinner join trello_card_member_relation tcmr \n\ton tcmr.trello_card_id = tc.trello_id \n\tleft join trello_members tm \n\ton tm.trello_id = tcmr.trello_member_id\n\tleft join trello_card_history tch \n\ton tch.trello_card_id = tc.trello_id\n\tleft join (\n\t\tselect \n\t\t\ttc2.trello_id as card_id,\n\t\t\tcount(tcmr2.trello_member_id) as member_count\n\t\tfrom trello_cards tc2 \n\t\tinner join trello_card_member_relation tcmr2 \n\t\ton tcmr2.trello_card_id = tc2.trello_id\n\t\twhere tc2.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\tgroup by tc2.trello_id\n\t) as mc\n\ton mc.card_id = tc.trello_id\n\twhere tl.name like 'type:%'\n\t\tand tch.trello_list_id = '5a2fc0b811bfc2a9b31cc852'\n\t\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\tand tm.trello_id in (${employee_id})\n\tgroup by tc.trello_id, tl.name\n) as result\ngroup by type\n"
    }
   ]
  },
  {
   "title": "Card type count",
   "type": "table",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "rawSql": "select\n\ttl.name as Type,\n\tsum(count) as Count\nfrom trello_cards tc \ninner join trello_card_label_relation tclr \non tclr.trello_card_id = tc.trello_id \ninner join trello_labels tl \non tl.trello_id  = tclr.trello_label_id \ninner join trello_card_member_relation tcmr \non tcmr.trello_card_id = tc.trello_id \nleft join trello_members tm \non tm.trello_id = tcmr.trello_member_id \nleft join (\n\t\tselect \n\t\t\ttc2.trello_id as card_id,\n\t\t\t1.0 / count(tcmr2.trello_member_id) as count\n\t\tfrom trello_cards tc2 \n\t\tinner join trello_card_member_relation tcmr2 \n\t\ton tcmr2.trello_card_id = tc2.trello_id\n\t\twhere tc2.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\tgroup by tc2.trello_id\n\t) as mc\non mc.card_id = tc.trello_id\nwhere tl.name like 'type:%'\n\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\tand tm.trello_id in (${employee_id})\ngroup by tl.name"
    }
   ]
  },
  {
   "title": "Story point cost",
   "type": "table",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select\n\ttype as Type,\n\tavg(story_cost) as Cost\nfrom (\n\tselect\n\t\ttl.name as type,\n\t\t(sum(tch.duration_minutes / mc.member_count) * 1.0 / (24.0 * 60) * tm.salary_per_day) / (tc.score * 1.0 / mc.member_count) as story_cost\n\tfrom trello_cards tc \n\tleft join trello_card_label_relation tclr \n\ton tclr.trello_card_id = tc.trello_id \n\tleft join trello_labels tl \n\ton tl.trello_id  = tclr.trello_label_id \n\tleft join trello_card_history tch \n\ton tch.trello_card_id = tc.trello_id \n\tleft join trello_card_member_relation tcmr \n\ton tcmr.trello_card_id = tc.trello_id \n\tleft join trello_members tm \n\ton tm.trello_id = tcmr.trello_member_id \n\tleft join (\n\t\tselect \n\t\t\ttc2.trello_id as card_id,\n\t\t\tcount(tcmr2.trello_member_id) as member_count\n\t\tfrom trello_cards tc2 \n\t\tinner join trello_card_member_relation tcmr2 \n\t\ton tcmr2.trello_card_id = tc2.trello_id\n\t\twhere tc2.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\tgroup by tc2.trello_id\n\t) as mc\n\ton mc.card_id = tc.trello_id\n\twhere tl.name like 'type:%'\n\t\tand tch.trello_list_id = '5a2fc0b811bfc2a9b31cc852'\n\t\tand tc.score != 0 and tc.score is not null\n\t\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\tand tm.trello_id in (${employee_id})\n\tgroup by tc.trello_id, tl.name, tc.score, mc.member_count, tm.salary_per_day\n) as result\ngroup by type"
    }
   ]
  },
  {
   "title": "Story point by type",
   "type": "table",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "rawSql": "select \n\ttl.name as Type,\n\tSUM(tc.score * 1.0 / mc.member_count) as Story\nfrom trello_cards tc \nleft join trello_card_label_relation tclr \non tclr.trello_card_id = tc.trello_id \nleft join trello_labels tl \non tl.trello_id = tclr.trello_label_id\ninner join trello_card_member_relation tcmr \non tcmr.trello_card_id = tc.trello_id \nleft join trello_members tm \non tm.trello_id = tcmr.trello_member_id \nleft join (\n\t\tselect \n\t\t\ttc2.trello_id as card_id,\n\t\t\tcount(tcmr2.trello_member_id) as member_count\n\t\tfrom trello_cards tc2 \n\t\tleft join trello_card_member_relation tcmr2 \n\t\ton tcmr2.trello_card_id = tc2.trello_id\n\t\twhere tc2.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\tgroup by tc2.trello_id\n\t) as mc\n\ton mc.card_id = tc.trello_id\nwhere tl.name like 'type:%'\n\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\tand tm.trello_id in (${employee_id})\ngroup by tl.name"
    }
   ]
  },
  {
   "title": "Bug cost",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select \n\tbug_complexity as Complexity,\n\tavg(cost) as Cost\nfrom (\nselect \n card_id,\n bug_complexity,\n sum(cost) as cost\nfrom (\n\tselect\n\t\ttc.trello_id as card_id,\n\t\tcase \n\t\t\twhen tc.score <= 3 then '1 easy'\n\t\t\twhen tc.score = 5 then '2 middle'\n\t\t\telse '3 hard'\n\t\tend as bug_complexity,\n\t\t(tch.duration_minutes / mc.member_count) / (24.0 * 60) * tm.salary_per_day as cost\n\tfrom trello_cards tc \n\tleft join trello_card_label_relation tclr \n\ton tclr.trello_card_id = tc.trello_id \n\tleft join trello_labels tl \n\ton tl.trello_id  = tclr.trello_label_id \n\tinner join trello_card_member_relation tcmr \n\ton tcmr.trello_card_id = tc.trello_id \n\tleft join trello_members tm \n\ton tm.trello_id = tcmr.trello_member_id \n\tleft join trello_card_history tch \n\ton tch.trello_card_id = tc.trello_id\n\tleft join (\n\t\tselect \n\t\t\ttc2.trello_id as card_id,\n\t\t\tcount(tcmr2.trello_member_id) as member_count\n\t\tfrom trello_cards tc2 \n\t\tleft join trello_card_member_relation tcmr2 \n\t\ton tcmr2.trello_card_id = tc2.trello_id\n\t\twhere tc2.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\tgroup by tc2.trello_id\n\t) as mc\n\ton mc.card_id = tc.trello_id\n\twhere tl.name like 'type: bug%'\n\t\tand tch.trello_list_id = '5a2fc0b811bfc2a9b31cc852'\n\t\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\tand tm.trello_id in (${employee_id})\n) as tasks\ngroup by card_id, bug_complexity\n) as result\ngroup by bug_complexity"
    }
   ]
  },
  {
   "title": "Bug count by complexity",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select \n    bug_complexity as Complexity,\n    SUM(count) as Count\nfrom (\n\tselect\n\t\ttc.trello_id as card_id,\n\t\ttcmr.trello_member_id as employee_id,\n\t\tcase \n\t\t\twhen tc.score <= 3 then '1 easy'\n\t\t\twhen tc.score = 5 then '2 middle'\n\t\t\telse '3 hard'\n\t\tend as bug_complexity,\n\t\ttl.name as label_name,\n\t\tmc.count as count\n\tfrom trello_cards tc \n\tinner join trello_card_label_relation tclr \n\ton tclr.trello_card_id = tc.trello_id \n\tinner join trello_labels tl \n\ton tl.trello_id  = tclr.trello_label_id \n\tinner join trello_card_member_relation tcmr \n\ton tcmr.trello_card_id = tc.trello_id \n\tleft join trello_members tm \n\ton tm.trello_id = tcmr.trello_member_id \n\tleft join (\n\t\tselect \n\t\t\ttc2.trello_id as card_id,\n\t\t\t1.0 / count(tcmr2.trello_member_id) as count\n\t\tfrom trello_cards tc2 \n\t\tleft join trello_card_member_relation tcmr2 \n\t\ton tcmr2.trello_card_id = tc2.trello_id\n\t\twhere tc2.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\tgroup by tc2.trello_id\n\t) as mc\n\ton mc.card_id = tc.trello_id\n\twhere tl.name like 'type: bug%'\n\t\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\tand tm.trello_id in (${employee_id})\n) as tasks\ngroup by bug_complexity\n"
    }
   ]
  },
  {
   "title": "Bug cost dynamic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select \n\tbug_complexity as Complexity,\n\tweek as Week,\n\tavg(cost) as Cost\nfrom (\nselect \n card_id,\n bug_complexity,\n week,\n sum(cost) as cost\nfrom (\n\tselect\n\t\ttc.trello_id as card_id,\n\t\tcase \n\t\t\twhen tc.score <= 3 then 'easy'\n\t\t\twhen tc.score = 5 then 'middle'\n\t\t\telse 'hard'\n\t\tend as bug_complexity,\n\t\tDATETRUNC(week, DATEADD(week, 1, done_time)) as week,\n\t\t(tch.duration_minutes / mc.member_count) / (24.0 * 60) * tm.salary_per_day as cost\n\tfrom trello_cards tc \n\tleft join trello_card_label_relation tclr \n\ton tclr.trello_card_id = tc.trello_id \n\tleft join trello_labels tl \n\ton tl.trello_id  = tclr.trello_label_id \n\tinner join trello_card_member_relation tcmr \n\ton tcmr.trello_card_id = tc.trello_id \n\tleft join trello_members tm \n\ton tm.trello_id = tcmr.trello_member_id \n\tleft join trello_card_history tch \n\ton tch.trello_card_id = tc.trello_id\n\tleft join (\n\t\tselect \n\t\t\ttc2.trello_id as card_id,\n\t\t\tcount(tcmr2.trello_member_id) as member_count\n\t\tfrom trello_cards tc2 \n\t\tleft join trello_card_member_relation tcmr2 \n\t\ton tcmr2.trello_card_id = tc2.trello_id\n\t\twhere tc2.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\tgroup by tc2.trello_id\n\t) as mc\n\ton mc.card_id = tc.trello_id\n\twhere tl.name like 'type: bug%'\n\t\tand tch.trello_list_id = '5a2fc0b811bfc2a9b31cc852'\n\t\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\tand tm.trello_id in (${employee_id})\n) as tasks\ngroup by card_id, bug_complexity, week\n) as result\ngroup by bug_complexity, week"
    }
   ]
  },
  {
   "title": "Task cost dynamic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "select \n\ttype as Type,\n\tweek as Week,\n\tavg(cost) as Cost\nfrom (\nselect \n\ttype,\n\tDATETRUNC(week, DATEADD(week, 1, done_time)) as week,\n\tsum(cost) as cost\nfrom (\n\tselect\n\t\ttc.trello_id as card_id,\n\t\ttm.trello_id  as employee_id,\n\t\ttl.name as type,\n\t\t(tch.duration_minutes / mc.member_count) / (24.0 * 60) * tm.salary_per_day as cost,\n\t\ttc.done_time as done_time\n\tfrom trello_cards tc \n\tleft join trello_card_label_relation tclr \n\ton tclr.trello_card_id = tc.trello_id \n\tleft join trello_labels tl \n\ton tl.trello_id  = tclr.trello_label_id \n\tinner join trello_card_member_relation tcmr \n\ton tcmr.trello_card_id = tc.trello_id \n\tleft join trello_members tm \n\ton tm.trello_id = tcmr.trello_member_id\n\tleft join trello_card_history tch \n\ton tch.trello_card_id = tc.trello_id\n\tleft join (\n\t\tselect \n\t\t\ttc2.trello_id as card_id,\n\t\t\tcount(tcmr2.trello_member_id) as member_count\n\t\tfrom trello_cards tc2 \n\t\tinner join trello_card_member_relation tcmr2 \n\t\ton tcmr2.trello_card_id = tc2.trello_id\n\t\twhere tc2.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\tgroup by tc2.trello_id\n\t) as mc\n\ton mc.card_id = tc.trello_id\n\twhere tl.name like 'type:%'\n\t\tand tch.trello_list_id = '5a2fc0b811bfc2a9b31cc852'\n\t\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\tand tm.trello_id in (${employee_id})\n) as tasks\ngroup by card_id, employee_id, type, DATETRUNC(week, DATEADD(week, 1, done_time))\n) as result\ngroup by type, week"
    }
   ]
  },
  {
   "title": "Story cost dynamic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "select \n\ttype as Type,\n\tweek as Week,\n\tavg(cost) as Cost\nfrom (\nselect \n\ttype,\n\tDATETRUNC(week, DATEADD(week, 1, done_time)) as week,\n\tsum(story_cost) as cost\nfrom (\n\tselect\n\t\ttc.trello_id as card_id,\n\t\ttm.trello_id  as employee_id,\n\t\ttl.name as type,\n\t\t((tch.duration_minutes / mc.member_count) / (24.0 * 60) * tm.salary_per_day) / (tc.score * 1.0 / mc.member_count) as story_cost,\n\t\ttc.done_time as done_time\n\tfrom trello_cards tc \n\tleft join trello_card_label_relation tclr \n\ton tclr.trello_card_id = tc.trello_id \n\tleft join trello_labels tl \n\ton tl.trello_id  = tclr.trello_label_id \n\tinner join trello_card_member_relation tcmr \n\ton tcmr.trello_card_id = tc.trello_id \n\tleft join trello_members tm \n\ton tm.trello_id = tcmr.trello_member_id\n\tleft join trello_card_history tch \n\ton tch.trello_card_id = tc.trello_id\n\tleft join (\n\t\tselect \n\t\t\ttc2.trello_id as card_id,\n\t\t\tcount(tcmr2.trello_member_id) as member_count\n\t\tfrom trello_cards tc2 \n\t\tinner join trello_card_member_relation tcmr2 \n\t\ton tcmr2.trello_card_id = tc2.trello_id\n\t\twhere tc2.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\tgroup by tc2.trello_id\n\t) as mc\n\ton mc.card_id = tc.trello_id\n\twhere tl.name like 'type:%'\n\t\tand tch.trello_list_id = '5a2fc0b811bfc2a9b31cc852'\n\t\tand tc.score != 0 and tc.score is not null\n\t\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n\t\tand tm.trello_id in (${employee_id})\n) as tasks\ngroup by card_id, employee_id, type, DATETRUNC(week, DATEADD(week, 1, done_time))\n) as result\ngroup by type, week"
    }
   ]
  },
  {
   "title": "Bugs with costs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bug cost table",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "select \n\ttype,\n\tISNULL(full_name, 'no assignee') as assignee,\n\tstory,\n\tcase\n\t\twhen story <= 3 then 'easy'\n\t\twhen story = 5 then 'medium'\n\t\telse 'hard'\n\tend as complexity,\n\turl,\n\tSUM(cost)\nfrom (\nselect \n\ttc.trello_id,\n\ttl.name as type,\n\ttm.full_name,\n\ttc.score as story,\n\ttc.short_url as url,\n\t((tch.duration_minutes * 1.0 / mc.member_count) / (24 * 60)) * tm.salary_per_day as cost\nfrom trello_cards tc \nleft join trello_card_history tch \non tch.trello_card_id = tc.trello_id \nleft join trello_card_member_relation tcmr \non tcmr.trello_card_id = tc.trello_id \nleft join trello_members tm \non tm.trello_id = tcmr.trello_member_id \nleft join trello_card_label_relation tclr \non tclr.trello_card_id = tc.trello_id \nleft join trello_labels tl \non tl.trello_id = tclr.trello_label_id\ninner join (\n\t\tselect \n\t\t\ttc2.trello_id as card_id,\n\t\t\tcount(tcmr2.trello_member_id) as member_count\n\t\tfrom trello_cards tc2 \n\t\tinner join trello_card_member_relation tcmr2 \n\t\ton tcmr2.trello_card_id = tc2.trello_id\n\t\tgroup by tc2.trello_id\n\t) as mc\non mc.card_id = tc.trello_id\nwhere tl.name like 'type:%'\n\tand tch.trello_list_id = '5a2fc0b811bfc2a9b31cc852'\n\tand tc.done_time between '${__from:date:iso}' and '${__to:date:iso}'\n) as tasks\ngroup by type, full_name, story, url"
      }
     ]
    }
   ]
  }
 ]
}